### ISSUE TITLE
When updating any post you get 'length' of likes undefined even if you clone the repo

### ISSUE THREAD

**Issue by galpodlipnik1** [adrianhajdin/project_mern_memories#115]

**Comment by nk1102** [comment]
Got any solution of it ?
Same issue I am facing @adrianhajdin 
please see

**Comment by bharatpaliwal-169** [comment]
@adrianhajdin Look into it this is a bug.

**Comment by shantanusharma6079** [comment]
> @adrianhajdin Look into it this is a bug.

In Post.js file write Likes component like this :

const Likes = () => {
    if (post?.likes?.length > 0) {

and it works!!
