### ISSUE TITLE
Google Sign in issue "popup_closed_by_user'" persists even after clearing cache

### ISSUE THREAD

**Issue by Leykwan132** [adrianhajdin/project_mern_memories#117]
I was still unable to log in even after clearing cache on macOs. Anyone facing this issue?

**Comment by VanoVasilyan** [comment]
Hi, I hope this will help))

Step 1. import { gapi } from 'gapi-script'
Step 2. use this code in your Auth component 

  useEffect(() => {
        function start() {
            gapi.auth2.init({
                client_id: clientId
            })
        }
        gapi.load('client:auth2', start)
    })

**Comment by VanoVasilyan** [comment]
> I was still unable to log in even after clearing cache on macOs. Anyone facing this issue?

Hi, I hope this will help))

Step 1. import { gapi } from 'gapi-script'
Step 2. use this code in your Auth component

useEffect(() => {
function start() {
gapi.auth2.init({
client_id: clientId
})
}
gapi.load('client:auth2', start)
})

**Comment by Leykwan132** [comment]
That did the magic! Thank you so much!

**Comment by VanoVasilyan** [comment]
> That did the magic! Thank you so much!

You are welcome ))
