### ISSUE TITLE
posts  are not displaying but they are updating in DB error:  hen called with an action of type "FETCH_ALL", the slice reducer for key "posts" returned undefined.

### ISSUE THREAD

**Issue by bhagathvikas** [adrianhajdin/project_mern_memories#136]
please provide a solution

**Comment by khrisdain** [comment]
please have you been able to solve this, i am having the same issue

**Comment by bhagathvikas** [comment]
check this line in client/actions/post in getPosts function 
const { data:{data,currentPage,numberOfPages} } = await api.fetchPosts(page);

and do check out reducer posts 
 return {...state,
      posts: action.payload.data,
      currentPage: action.payload.currentPage,
      numberOfPages: action.payload.numberOfPages
      }

**Comment by khrisdain** [comment]
Thank you brother God bless
