### ISSUE TITLE
Does not work, even when copying the full repository

### ISSUE THREAD

**Issue by ThomasAurelius** [adrianhajdin/project_mern_memories#137]
I finished the tutorial, and went through and verified no spelling errors, and still wasn't working, so I copied the whole repository, from part 6 and ran it... and still doesn't work. Posts don't ever load. My mongoose settings are correct.

**Comment by 0xMALVEE** [comment]
probably the qauth problem. since google has new api now the google identity services. here you can check my latest video on how to use it https://youtu.be/TqlVP_IkS28

**Comment by philip06lee** [comment]
got do those npm installs

**Comment by Gagenrllc** [comment]
> I finished the tutorial, and went through and verified no spelling errors, and still wasn't working, so I copied the whole repository, from part 6 and ran it... and still doesn't work. Posts don't ever load. My mongoose settings are correct.

Do you mind showing the console errors ?  I wonder if you are seeing some of my issues.

**Comment by rizkymhmd2k** [comment]
had you set the proxy from client to your local?

**Comment by Gagenrllc** [comment]
> had you set the proxy from client to your local?

Yes.  I think I was able to resolve this by using configureStore.

The way I set it up was like this.

-- Store.js

```
import {configureStore} from '@reduxjs/toolkit';
import postsReducer from './features/posts/postsSlice.js';

export const store = configureStore({
    reducer: {
        posts: postsReducer,
    },
});

export default store;
```

Also this, postSlice.js

```
import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    posts:[],
    isLoading: true
}

const postsSlice = createSlice(
    {
        name:'posts',
        initialState
    }
)

export default postsSlice.reducer;
```
