### ISSUE TITLE
problem with the server side

### ISSUE THREAD

**Issue by DayoAsaolu** [adrianhajdin/project_mern_memories#15]
I am just at the 15:41 min:sec line in the youtube video. I am getting this error. Pls help. Thank you

![image](https://user-images.githubusercontent.com/53376175/108438827-9ccff780-722a-11eb-866f-d5ed53c2c7b7.png)

**Comment by DayoAsaolu** [comment]
i upgraded node to 14

**Comment by kocak-ilyas** [comment]
in package.json
change
start:'node to ' nodemon

19 Şub 2021 Cum 03:24 tarihinde Dayo Asaolu <notifications@github.com> şunu
yazdı:
