### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by MadhaneeswaranP** [adrianhajdin/project_mern_memories#28]
GET http://localhost:5000/posts 404 (Not Found)

**Comment by patrick022** [comment]
Its a typo 
in your server routes file change the router.get to router.post
So basically you're requesting get instead of posting to the database.
:)
![image](https://user-images.githubusercontent.com/50113800/115660599-d3330b80-a36e-11eb-8ef1-8295e16b0ba1.png)

**Comment by MadhaneeswaranP** [comment]
I think i did properly? Anyway I uploaded the SS check out


![Screenshot (90)](https://user-images.githubusercontent.com/78028332/115713187-59f9df80-a393-11eb-81dc-556462389c12.png)

Take a look at the error im getting at client side

![Screenshot (89)](https://user-images.githubusercontent.com/78028332/115713419-9cbbb780-a393-11eb-89c0-6a148335c8cc.png)

**Comment by MadhaneeswaranP** [comment]
Resolved. Typo Error in Client api request
