### ISSUE TITLE
Login page is  not coming

### ISSUE THREAD

**Issue by VibhuGautam** [adrianhajdin/project_mern_memories#51]
Is someone facing this issue. Whenever you logged out and click on the signIn button it just goes to /posts page only. If  I refresh the page then it's working fine. 
Any idea why this  is happening ?

**Comment by VibhuGautam** [comment]
I found  the error it was in this :
const token = jwt.sign({ email: oldUser.email, id: oldUser._id }, secret, { expiresIn: "1min" }); 
If its 1 min and then I click on the Sign In button then it goes to  auth page.

**Comment by tjbarrett42** [comment]
Did you find a solution for this?
