### ISSUE TITLE
Cant retrieve data from Backend Server

### ISSUE THREAD

**Issue by Hassaan0316** [adrianhajdin/project_mern_memories#6]
First of all thanks for your efforts!
Whenever i start my application again or refresh the app, the POSTS which are saved in database are not showing. But when i insert new POST it works fine. In short i have tested few things and came to know that whenever i start my application at localhost the GET method from backend is not called. Please help me.
If you need any code to check than please message

**Comment by ghost** [comment]
Did you ever solve this issue? I have the same problem.
