### ISSUE TITLE
Slow Loading Screen while fetching posts from database

### ISSUE THREAD

**Issue by warmachine028** [adrianhajdin/project_mern_memories#86]
Posts are loading very slow after adding chat section in 5th part. Is there any way to make it fast ?

**Comment by LameckMeshack** [comment]
Sure am even thinking of using MongoDB compass than atlas

**Comment by shubhamy4ever** [comment]
mongo db compass is gui for either local database or else cluster(atlas) which means u can't use compass as local database because then the memories project database will be unaccesible to others users and will not be on cloud

**Comment by LameckMeshack** [comment]
Sure ...but I only use for development during deployment I'll connect it to
the Atlas

**Comment by shubhamy4ever** [comment]
ok

**Comment by abdullahalnomandev** [comment]
I'm fetching the same issue. It takes around 1-2 minutes to fetch. how to solve it?

**Comment by warmachine028** [comment]
> I'm fetching the same issue. It takes around 1-2 minutes to fetch. how to solve it?

*Facing

**Comment by warmachine028** [comment]
## I have tried a different solution to fix this, it's redundant but clever.
1. All post images are compressed(<1mb) and a thumbnail (<100kb) is generated on Creation and Updation.
2. The thumbnails instead of the actual image are stored in the post document.
3. The actual compressed media are stored in a different collection named **Media**.
4. During Bulk fetching of posts we are only fetching the documents from Post collection which has lower size putting less stress on server. Also we can compromise on image quality in this scenario since we are seeing the small thumbnails anyway. This leads to a significantly faster fetching time.
5. Whereas during fetching an individual post we replace the thumbnail with actual post image from the Media collection.
6. This solved the slower fetching issue and retains the image quality.
7. Drawback: yes we have to make 2 queries and the data is now redundant in the database but we have to make some compromises to improve and fix this major issue.


Here is my [repo link](https://github.com/warmachine028/memories). I have a detailed ERD in the README too.
